// This file is generated by Firebase Studio.

'use server';

/**
 * @fileOverview A flow to generate an AI explanation of the project's health score.
 *
 * - generateHealthScoreExplanation - A function that generates a health score explanation.
 * - GenerateHealthScoreExplanationInput - The input type for the generateHealthScoreExplanation function.
 * - GenerateHealthScoreExplanationOutput - The return type for the generateHealthScoreExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateHealthScoreExplanationInputSchema = z.object({
  healthScore: z.number().describe('The overall health score of the project (0-100).'),
  vulnerabilities: z.array(z.string()).describe('A list of vulnerabilities found in the project.'),
});

export type GenerateHealthScoreExplanationInput = z.infer<typeof GenerateHealthScoreExplanationInputSchema>;

const GenerateHealthScoreExplanationOutputSchema = z.object({
  explanation: z.string().describe('An AI-generated explanation of the health score, including factors and improvement suggestions.'),
});

export type GenerateHealthScoreExplanationOutput = z.infer<typeof GenerateHealthScoreExplanationOutputSchema>;

export async function generateHealthScoreExplanation(input: GenerateHealthScoreExplanationInput): Promise<GenerateHealthScoreExplanationOutput> {
  return generateHealthScoreExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateHealthScoreExplanationPrompt',
  input: {schema: GenerateHealthScoreExplanationInputSchema},
  output: {schema: GenerateHealthScoreExplanationOutputSchema},
  prompt: `You are a Senior Security Engineer explaining the health score of a project.

  The project has a health score of {{healthScore}}.
  The following vulnerabilities were found: {{#each vulnerabilities}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}.

  Explain the factors influencing the score and how to improve it. Provide specific and actionable recommendations.
`,
});

const generateHealthScoreExplanationFlow = ai.defineFlow(
  {
    name: 'generateHealthScoreExplanationFlow',
    inputSchema: GenerateHealthScoreExplanationInputSchema,
    outputSchema: GenerateHealthScoreExplanationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
